### PR TITLE
e2e for code interpreter directly api access

### LINKED ISSUE #178: Why do the e2e run python code locally？
```
// executeCode executes code through the CodeInterpreter API using Python SDK
func (e *testEnv) executeCode(namespace, name string, req *CodeExecuteRequest) (*CodeExecuteResponse, string, error) {
	// Create a temporary Python file
	tmpFile, err := os.CreateTemp("", "e2e-code-exec-*.py")
	if err != nil {
		return nil, "", fmt.Errorf("failed to create temp file: %w", err)
	}
	defer os.Remove(tmpFile.Name())

	// Create a Python script that uses the agentcube SDK
	// Note: Not using 'with' statement to keep session alive for test verification
	pythonScript := fmt.Sprintf(`
import os
import sys
import json

# Set environment variables
os.environ['ROUTER_URL'] = %q
os.environ['WORKLOAD_MANAGER_URL'] = %q
if %q:
    os.environ['API_TOKEN'] = %q

# Add SDK to path
sys.path.insert(0, '/root/agentcube/sdk-python')

from agentcube import CodeInterpreterClient

try:
    client = CodeInterpreterClient(name=%q, namespace=%q)
    result = client.run_code(%q, %q)
    # Output as JSON for easy parsing
    output = {
        'stdout': result,
        'stderr': '',
        'exit_code': 0,
        'session_id': client.session_id
    }
    print(json.dumps(output))
except Exception as e:
    # Return error in expected format
    output = {
        'stdout': '',
        'stderr': str(e),
        'exit_code': 1,
        'session_id': ''
    }
    print(json.dumps(output))
    sys.exit(1)
`, e.routerURL, e.workloadMgrURL, e.authToken, e.authToken, name, namespace, req.Language, req.Code)

	// Write the Python script to the temp file
	if _, err := tmpFile.WriteString(pythonScript); err != nil {
		return nil, "", fmt.Errorf("failed to write temp file: %w", err)
	}
	tmpFile.Close()

	// Execute the Python file with timeout
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	//nolint:gosec // G204: tmpFile.Name() is controlled by this test, not user input
	cmd := exec.CommandContext(ctx, "python3", tmpFile.Name())
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err = cmd.Run()
	output := stdout.String()

	// If stderr has content but stdout is empty, use stderr as output for error info
	if output == "" && stderr.Len() > 0 {
		output = stderr.String()
	}

	// Parse the JSON output
	var jsonOutput struct {
		Stdout    string `json:"stdout"`
		Stderr    string `json:"stderr"`
		ExitCode  int    `json:"exit_code"`
		SessionID string `json:"session_id"`
	}

	if err := json.Unmarshal([]byte(output), &jsonOutput); err != nil {
		return nil, "", fmt.Errorf("failed to parse python output: %w, output: %s, stderr: %s", err, output, stderr.String())
	}

	response := &CodeExecuteResponse{
		Output:   jsonOutput.Stdout,
		Error:    jsonOutput.Stderr,
		ExitCode: jsonOutput.ExitCode,
	}
```

/assign @YaoZengzeng 

I guess this is a mistake from ai coding

### PR DESCRIPTION
**Pull request by YaoZengzeng**
**What type of PR is this?**

/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #178

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/workloadmanager/handlers.go [hunk 1]
```diff
@@ -104,7 +104,7 @@ func (s *Server) handleSandboxCreate(c *gin.Context, kind string) {
 		if errors.Is(err, api.ErrAgentRuntimeNotFound) || errors.Is(err, api.ErrCodeInterpreterNotFound) {
 			respondError(c, http.StatusNotFound, err.Error())
 		} else {
-			respondError(c, http.StatusInternalServerError, "internal server error")
+			respondError(c, http.StatusInternalServerError, err.Error())
```
Comment (hzxuzhonghu) [inline pkg/workloadmanager/handlers.go]: Deliberately hide the error details

Comment (YaoZengzeng) [reply pkg/workloadmanager/handlers.go]: Just for debug, will cleanup later.

File: pkg/workloadmanager/k8s_client.go [hunk 2]
```diff
@@ -288,8 +289,38 @@ func (u *UserK8sClient) DeleteSandboxClaim(ctx context.Context, namespace, sandb
...
+// GetSandboxPodIP gets the IP address of the pod corresponding to the Sandbox with retry logic
+func (c *K8sClient) GetSandboxPodIP(ctx context.Context, namespace, sandboxName, podName string) (string, error) {
+	retryCtx, cancel := context.WithTimeout(ctx, 20*time.Second)
+	defer cancel()
+	ticker := time.NewTicker(time.Second)
+	defer ticker.Stop()
+
+	var ip string
+	var err error
+	for {
```
Comment (hzxuzhonghu) [inline pkg/workloadmanager/k8s_client.go]: donot we have already guranteed it is ready before calling `GetSandboxPodIP`
How can ip not assigned when it is ready

File: test/e2e/e2e_test.go [hunk 3]
```diff
@@ -594,11 +629,64 @@ func TestCodeInterpreterWarmPool(t *testing.T) {
...
+				}
+			}
+			if tc.expectStderr != "" {
+				if resp.Stderr != tc.expectStderr {
+					t.Errorf("Expected stderr %q, got %q", tc.expectStderr, resp.Stderr)
+				}
+			}
+			if resp.ExitCode != tc.expectExit {
+				t.Errorf("Expected exit code %d, got %d", tc.expectExit, resp.ExitCode)
+			}
```
[the remark this answers is not in the document]
Comment (YaoZengzeng) [reply test/e2e/e2e_test.go]: fixed

**Comment by YaoZengzeng** [comment]
@hzxuzhonghu ptal

**Review by hzxuzhonghu — COMMENTED** [review]
A bit step further, this is almost writing a go-sdk, that's should be in our roadmap

**Comment by YaoZengzeng** [comment]
ping @hzxuzhonghu

**Comment by YaoZengzeng** [comment]
> @hzxuzhonghu please merge

ping @hzxuzhonghu

**Comment by YaoZengzeng** [comment]
ping @hzxuzhonghu
