### PR TITLE
fix(crd): align AgentRuntime CRD with CodeInterpreter annotations and types

### LINKED ISSUE #209: AgentRuntime CRD is Missing Critical Annotations and Types
### Description

The `AgentRuntime` CRD is missing several critical kubebuilder annotations and type definitions that are present in the similar `CodeInterpreter` CRD, causing inconsistency and potential issues with typed client generation.

### Current Issues

1. **Missing kubebuilder annotations** - No `+genclient`, `+k8s:deepcopy-gen:interfaces`, `+kubebuilder:subresource:status`, or `+kubebuilder:printcolumn` annotations
2. **Missing `AgentRuntimeList` type** - Required for Kubernetes list operations
3. **Empty `AgentRuntimeStatus` struct** - Cannot report readiness or conditions
4. **Missing `DeepCopyObject()` method** in generated code - Required for typed client-go usage

**File:** `pkg/apis/runtime/v1alpha1/agent_type.go` (Lines 18-28)

Current state:
```go
// AgentRuntime defines the desired state of an agent runtime environment.
type AgentRuntime struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty,omitzero" protobuf:"bytes,1,opt,name=metadata"`
	Spec   AgentRuntimeSpec   `json:"spec" protobuf:"bytes,2,opt,name=spec"`
	Status AgentRuntimeStatus `json:"status" protobuf:"bytes,3,opt,name=status"`
}
```

Compare to `CodeInterpreter` in `codeinterpreter_types.go` (Lines 29-42):
```go
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type CodeInterpreter struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec   CodeInterpreterSpec   `json:"spec"`
	Status CodeInterpreterStatus `json:"status,omitempty"`
}
```

**Generated code comparison:**

`CodeInterpreter` has `DeepCopyObject()` method in `zz_generated.deepcopy.go`:
```go
func (in *CodeInterpreter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
```

`AgentRuntime` is missing this method entirely.

Image

**CRD Manifest comparison:**

CodeInterpreter CRD has printer columns:
```bash
$ grep -A 3 "additionalPrinterColumns:" manifests/charts/base/crds/runtime.agentcube.volcano.sh_codeinterpreters.yaml
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
```

AgentRuntime CRD does not:
```bash
$ grep "additionalPrinterColumns:" manifests/charts/base/crds/runtime.agentcube.volcano.sh_agentruntimes.yaml
# No output - not found
```

### Impact

- **Typed client generation** - Cannot generate proper typed clients for AgentRuntime
- **List operations** - Missing `AgentRuntimeList` type breaks list functionality
- **kubectl UX** - No Age column in `kubectl get agentruntimes` output
- **Status updates** - Cannot report readiness or conditions to users
- **Inconsistency** - Two similar runtime CRDs have different structures

### PR DESCRIPTION
**Pull request by mahil-2040**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR adds missing kubebuilder annotations and types to the AgentRuntime CRD to achieve consistency with the CodeInterpreter CRD and enable proper typed client-go generation.

## Changes

- Added kubebuilder annotations (`+genclient`, `+k8s:deepcopy-gen:interfaces`, `+kubebuilder:object:root=true`, `+kubebuilder:subresource:status`, etc.) to the `AgentRuntime` type
- Added `AgentRuntimeList` type for Kubernetes list operations
- Added `Conditions` field to `AgentRuntimeStatus` to enable status reporting
- Added type metadata variables in `register.go` (`AgentRuntimeKind`, etc.)
- Generated typed clientset, informers, and listers for `AgentRuntime`
- Added `Age` column to `kubectl get agentruntimes` output via `additionalPrinterColumns`
- Enabled status subresource in the AgentRuntime CRD manifest

**Which issue(s) this PR fixes**:
Fixes #209 

**Special notes for your reviewer**:

Most files in `client-go` and the CRD manifest are auto-generated by `make gen-all` (which runs `controller-gen`, `client-gen`, `lister-gen`, and `informer-gen`).

The core manual changes are limited to:

- `agent_type.go` — added kubebuilder annotations, `AgentRuntimeList`, and status fields
- `register.go` — added type metadata variables
- `agentruntime.go` — fixed `.GroupResource()` call to match the `CodeInterpreter` pattern

## Verification

- `make gen-check`
- `make lint`

All checks pass successfully.

**Does this PR introduce a user-facing change?**:

```release-note
AgentRuntime CRD now includes status subresource and Age column in kubectl output. Status can be updated independently to report runtime readiness and conditions.
```

### CODE REVIEW

File: pkg/apis/runtime/v1alpha1/agent_type.go [hunk 1]
```diff
@@ -53,7 +58,15 @@ type AgentRuntimeSpec struct {
...
 
+// AgentRuntimeStatus represents the observed state of an AgentRuntime.
 type AgentRuntimeStatus struct {
+	// Conditions represent the latest available observations of the AgentRuntime's state
+	// +optional
+	Conditions []metav1.Condition `json:"conditions,omitempty"`
+
+	// Ready indicates whether the AgentRuntime is ready to serve requests
+	// +optional
+	Ready bool `json:"ready,omitempty"`
```
Comment (hzxuzhonghu) [inline pkg/apis/runtime/v1alpha1/agent_type.go]: can you please remove this first,  I would rather vote for `Accepted` than `Ready`

Comment (mahil-2040) [reply pkg/apis/runtime/v1alpha1/agent_type.go]: Done, can you check it now?

**Comment by mahil-2040** [comment]
hey @hzxuzhonghu i have made the changes you asked for can you take a look at it?

File: pkg/apis/runtime/v1alpha1/agent_type.go [hunk 2]
```diff
@@ -22,17 +22,22 @@ import (
 )
 
 // AgentRuntime defines the desired state of an agent runtime environment.
+// +genclient
+// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
+// +kubebuilder:object:root=true
+// +kubebuilder:subresource:status
+// +kubebuilder:resource:scope=Namespaced
+// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
```
Comment (hzxuzhonghu) [inline pkg/apis/runtime/v1alpha1/agent_type.go:30]: can you please show the kubectl get AgentRuntime  output?

I guess this is generated by AI

Comment (mahil-2040) [reply pkg/apis/runtime/v1alpha1/agent_type.go:30]: Thanks for the review and merge!

To clarify regarding the code style - I used CodeInterpreter it as a direct reference to ensure AgentRuntime has consistent behavior and structure. That similarity is intentional, not just auto-generated.
Here is the kubectl get agentruntimes output from my local verification, it confirms that AGE column is present and working as expected:

image
